create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text not null unique,
  password_hash text not null
);

alter table public.usuarios enable row level security;
create policy "Allow anon all" on public.usuarios
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

alter table public.categorias enable row level security;
create policy "Allow anon all" on public.categorias
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  descripcion text default '',
  precio_compra double precision not null default 0,
  precio_venta double precision not null default 0,
  stock_actual integer not null default 0,
  stock_minimo integer not null default 5,
  por_encargo boolean not null default false,
  categoria_id bigint references public.categorias(id)
);

alter table public.productos enable row level security;
create policy "Allow anon all" on public.productos
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text default ''
);

alter table public.clientes enable row level security;
create policy "Allow anon all" on public.clientes
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.pedidos_encargo (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id),
  cliente_id bigint references public.clientes(id),
  estado text not null default 'pendiente',
  fecha_solicitud timestamptz not null default now(),
  fecha_estimada timestamptz
);

alter table public.pedidos_encargo enable row level security;
create policy "Allow anon all" on public.pedidos_encargo
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  usuario_id bigint references public.usuarios(id),
  cliente_id bigint references public.clientes(id),
  total double precision not null default 0
);

alter table public.ventas enable row level security;
create policy "Allow anon all" on public.ventas
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.detalles_venta (
  id bigint generated by default as identity primary key,
  venta_id bigint references public.ventas(id),
  producto_id bigint references public.productos(id),
  cantidad integer not null,
  precio_unitario double precision not null default 0
);

alter table public.detalles_venta enable row level security;
create policy "Allow anon all" on public.detalles_venta
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  categoria text not null,
  descripcion text default '',
  monto double precision not null default 0,
  usuario_id bigint references public.usuarios(id)
);

alter table public.gastos enable row level security;
create policy "Allow anon all" on public.gastos
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.productos(id),
  fecha timestamptz not null default now(),
  tipo text not null,
  cantidad integer not null,
  stock_antes integer not null,
  stock_despues integer not null,
  motivo text default '',
  venta_id bigint references public.ventas(id)
);

alter table public.movimientos_inventario enable row level security;
create policy "Allow anon all" on public.movimientos_inventario
  for all
  using (auth.role() = 'anon')
  with check (auth.role() = 'anon');

insert into public.categorias (nombre)
select 'Repuestos' where not exists (select 1 from public.categorias where nombre = 'Repuestos');
insert into public.categorias (nombre)
select 'Lubricantes' where not exists (select 1 from public.categorias where nombre = 'Lubricantes');
insert into public.categorias (nombre)
select 'Herramientas' where not exists (select 1 from public.categorias where nombre = 'Herramientas');
insert into public.categorias (nombre)
select 'Eléctrico' where not exists (select 1 from public.categorias where nombre = 'Eléctrico');
insert into public.categorias (nombre)
select 'Llantas' where not exists (select 1 from public.categorias where nombre = 'Llantas');
insert into public.categorias (nombre)
select 'Otros' where not exists (select 1 from public.categorias where nombre = 'Otros');

insert into public.usuarios (nombre, correo, password_hash)
select 'Administrador', 'admin@taller.com', 'e10adc3949ba59abbe56e057f20f883e'
where not exists (select 1 from public.usuarios where correo = 'admin@taller.com');
